name: marvel_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: 0.10.0-nullsafety.2
  get_it: ^7.2.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.0
  retrofit: ^2.0.1
  logger: ^1.0.0
  dio: ^4.0.0
  cached_network_image: ^3.1.0
  moor_flutter: ^4.0.0
  internet_connection_checker: ^0.0.1+2
  flutter_dotenv: ^5.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.11
  retrofit_generator: any
  moor_generator: any
  json_serializable: any
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - .env